const metrics = [
  { label: "Faturamento", icon: "payments", iconClass: "text-primary", value: "R$ 32.480", valueClass: "text-on-surface", detail: "+14% vs. mês ant." },
  { label: "Vendas", icon: "receipt_long", iconClass: "text-secondary", value: "648", valueClass: "text-on-surface", detail: "+22 pedidos" },
  { label: "Ticket Médio", icon: "shopping_bag", iconClass: "text-tertiary", value: "R$ 50,12", valueClass: "text-on-surface", detail: "Média saudável", neutral: true },
  { label: "Lucro Líquido", icon: "account_balance_wallet", iconClass: "text-primary-container", value: "R$ 6.840", valueClass: "text-primary-container", detail: "Margem líquida 21%" },
];

const weeks = [
  { value: "R$ 6.2k", week: "Sem 1", height: "h-[48%]", bar: "bg-surface-dim", strong: false },
  { value: "R$ 7.8k", week: "Sem 2", height: "h-[60%]", bar: "bg-surface-dim", strong: false },
  { value: "R$ 8.9k", week: "Sem 3", height: "h-[74%]", bar: "bg-primary", strong: false },
  { value: "R$ 9.5k", week: "Sem 4", height: "h-[88%]", bar: "bg-primary-container shadow-sm origin-bottom hover:scale-y-105", strong: true },
];

const margins = [
  { label: "Acessórios & Coleiras", value: "50,0%", width: "w-1/2", color: "bg-primary-container", text: "text-primary" },
  { label: "Higiene & Banho", value: "42,0%", width: "w-[42%]", color: "bg-tertiary-container", text: "text-primary" },
  { label: "Petiscos & Snacks", value: "38,0%", width: "w-[38%]", color: "bg-primary-fixed-dim", text: "text-primary" },
  { label: "Ração Seca & Úmida", value: "23,3%", width: "w-[23.3%]", color: "bg-secondary", text: "text-secondary" },
];

export function WarmDashboard() {
  return (
    <section className="w-full bg-surface-container-low py-space-2xl" id="dashboard"><div className="mx-auto flex max-w-[1440px] flex-col items-center px-margin-mobile md:px-margin"><div className="mb-space-xl max-w-2xl text-center"><span className="mb-space-xs block font-label-sm text-label-sm font-bold uppercase tracking-widest text-primary">Demonstração Interativa</span><h2 className="font-headline-lg-mobile text-headline-lg-mobile font-extrabold text-on-surface md:font-headline-lg md:text-headline-lg">Veja o que está acontecendo na sua loja.</h2><p className="mt-2 font-body-lg text-body-lg text-on-surface-variant">Uma visão clara, sem complicação, para você tomar decisões certas todos os dias.</p></div><div className="w-full max-w-5xl rounded-3xl bg-surface-container-lowest p-space-md shadow-xl md:p-space-xl"><div className="flex flex-col items-start justify-between gap-3 pb-space-md sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="h-3 w-3 rounded-full bg-primary-container" /><div><p className="font-title-md text-title-md font-bold text-on-surface">Painel de Desempenho Mensal</p><p className="font-body-sm text-body-sm text-on-surface-variant">Atualizado há 3 minutos · Modo consolidado</p></div></div><div className="flex items-center gap-2"><span className="rounded-lg bg-surface-container px-3 py-1.5 font-label-sm text-label-sm font-medium text-on-surface">Mês Vigente: Outubro</span><button aria-label="Baixar relatório" className="rounded-lg bg-primary-container p-1.5 text-on-primary transition-colors hover:bg-primary" type="button"><span className="material-symbols-outlined text-[18px]">file_download</span></button></div></div>
        <div className="mb-space-lg grid grid-cols-2 gap-space-sm md:grid-cols-4 md:gap-space-md">{metrics.map((metric) => (<div className="rounded-2xl bg-surface-container-low p-space-md" key={metric.label}><div className="mb-1 flex items-center justify-between"><span className="font-label-sm text-label-sm text-on-surface-variant">{metric.label}</span><span className={`material-symbols-outlined text-[18px] ${metric.iconClass}`}>{metric.icon}</span></div><p className={`font-headline-md text-headline-md font-extrabold ${metric.valueClass}`}>{metric.value}</p><span className={metric.neutral ? "mt-1 block font-label-sm text-label-sm font-semibold text-on-surface-variant" : "mt-1 flex items-center gap-0.5 font-label-sm text-label-sm font-semibold text-emerald-700"}>{metric.neutral ? null : <span className="material-symbols-outlined text-[14px]">arrow_upward</span>}{metric.detail}</span></div>))}</div>
        <div className="grid grid-cols-1 gap-space-lg lg:grid-cols-12"><div className="flex flex-col justify-between rounded-2xl bg-surface-container-low p-space-lg lg:col-span-7"><div className="mb-space-sm flex items-center justify-between"><div><p className="font-title-md text-title-md font-bold text-on-surface">Evolução de Vendas & Faturamento</p><p className="font-body-sm text-body-sm text-on-surface-variant">Últimas 4 semanas consolidadas</p></div><span className="rounded-full bg-primary-fixed px-2.5 py-1 font-label-sm text-label-sm font-bold text-on-primary-fixed">Constante alta</span></div><div className="flex h-48 w-full items-end justify-between gap-4 px-2 pt-4">{weeks.map((week) => (<div className="flex h-full flex-1 flex-col items-center justify-end gap-2" key={week.week}><span className={`font-label-sm text-label-sm ${week.strong ? "font-bold text-primary-container" : "text-on-surface-variant"}`}>{week.value}</span><div className={`w-full rounded-t-lg transition-all hover:opacity-80 ${week.height} ${week.bar}`} /><span className={`font-label-sm text-label-sm ${week.strong ? "font-bold text-primary-container" : "font-semibold text-on-surface"}`}>{week.week}</span></div>))}</div><div className="flex items-center justify-center gap-6 pt-3"><div className="flex items-center gap-2"><span className="h-3 w-3 rounded bg-surface-dim" /><span className="font-label-sm text-label-sm text-on-surface-variant">Vendas Regulares</span></div><div className="flex items-center gap-2"><span className="h-3 w-3 rounded bg-primary-container" /><span className="font-label-sm text-label-sm font-semibold text-on-surface">Semana Recorde</span></div></div></div>
          <div className="flex flex-col justify-between rounded-2xl bg-surface-container-low p-space-lg lg:col-span-5"><div><div className="mb-1 flex items-center justify-between"><p className="font-title-md text-title-md font-bold text-on-surface">Onde está seu dinheiro?</p><span className="material-symbols-outlined text-[18px] text-outline">pie_chart</span></div><p className="mb-space-md font-body-sm text-body-sm text-on-surface-variant">Margem de contribuição por departamento</p><div className="space-y-4">{margins.map((margin) => (<div key={margin.label}><div className="mb-1 flex justify-between font-label-md text-label-md"><span className="font-semibold text-on-surface">{margin.label}</span><span className={`font-bold ${margin.text}`}>{margin.value}</span></div><div className="h-3 w-full overflow-hidden rounded-full bg-surface-container"><div className={`h-full rounded-full ${margin.width} ${margin.color}`} /></div></div>))}</div></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-surface-container-lowest p-3"><span className="material-symbols-outlined text-[20px] text-primary-container">lightbulb</span><p className="font-body-sm text-body-sm text-on-surface">Dica do sistema: Otimize combos de ração com petiscos para subir a margem média em 8%.</p></div></div>
        </div></div></div></section>
  );
}
