"use client";

import Image from "next/image";
import { useState } from "react";
import { BrandLogo } from "@/components/common/BrandLogo";

const stockCards = [
  { icon: "warehouse", iconClass: "bg-secondary-fixed text-on-secondary-fixed", badge: "Equilibrado", badgeClass: "bg-emerald-100 text-emerald-800", title: "Estoque Atual", value: "R$ 54.200", valueClass: "text-on-surface", description: "Total avaliado em prateleira. 1.420 SKUs monitorados e catalogados com margens calculadas." },
  { icon: "warning", iconClass: "bg-error-container text-error", badge: "3 Alertas", badgeClass: "bg-error-container text-on-error-container", title: "Estoque Crítico", value: "12 itens", valueClass: "text-error", description: "Produtos com menos de 3 dias de cobertura de venda. Sugestão automática de compras gerada." },
  { icon: "hourglass_empty", iconClass: "bg-tertiary-fixed text-tertiary", badge: "Ação sugerida", badgeClass: "bg-tertiary-fixed text-on-tertiary-fixed", title: "Produtos Parados", value: "R$ 3.890", valueClass: "text-tertiary", description: "Capital parado há mais de 45 dias sem giro. Ideais para liquidações relâmpago ou combos promocionais." },
];

const stockItems = [
  { icon: "pets", iconClass: "text-primary", name: "Ração Premium Porte Médio 15kg", detail: "Giro médio: 12 un/semana", badge: "8 un em estoque", badgeClass: "bg-emerald-100 text-emerald-800" },
  { icon: "medication", iconClass: "text-tertiary", name: "Antipulgas & Carrapatos 10-20kg", detail: "Giro médio: 18 un/semana", badge: "2 un (Crítico)", badgeClass: "bg-amber-100 text-amber-800" },
  { icon: "local_mall", iconClass: "text-secondary", name: "Areia Higiênica Biodegradável 4kg", detail: "Giro médio: 35 un/semana", badge: "44 un em estoque", badgeClass: "bg-emerald-100 text-emerald-800" },
];

const faqs = [
  ["O que é o Flux Pet?", "Um sistema de gestão completo e simples feito sob medida para pet shops controlarem vendas, estoque e finanças em uma tela organizada e sem jargões contábeis complexos."],
  ["O Flux Pet controla estoque?", "Sim. Acompanhe entradas, saídas, níveis críticos e saiba exatamente quais itens estão parados há mais tempo para planejar compras assertivas e evitar desperdício."],
  ["Consigo acompanhar meu lucro?", "Sim. O sistema calcula automaticamente CMV, custos e margem para mostrar seu lucro líquido real por dia, semana e mês, permitindo saber quanto dinheiro realmente sobra."],
  ["Posso emitir nota fiscal?", "Sim, através de integração direta e simplificada com emissores homologados para NFC-e e NF-e com envio de comprovante direto por WhatsApp para os tutores."],
] as const;

export function WarmFinance() {
  return (
    <section className="mx-auto w-full max-w-[1440px] px-margin-mobile py-space-2xl md:px-margin"><div className="relative flex flex-col items-center justify-between gap-space-lg overflow-hidden rounded-3xl bg-surface-container-high p-space-xl md:flex-row md:p-space-2xl"><div className="z-10 max-w-2xl"><span className="mb-2 block font-label-sm text-label-sm font-bold uppercase tracking-wider text-primary">Diferencial Essencial</span><h2 className="mb-space-sm font-headline-lg-mobile text-headline-lg-mobile font-extrabold tracking-tight text-on-surface md:font-headline-lg md:text-headline-lg">Faturar é importante. Saber quanto sobra é essencial.</h2><p className="mb-space-md font-body-lg text-body-lg text-on-surface-variant">O Flux Pet mostra o faturamento, os custos, a margem e o lucro do seu negócio em tempo real. Pare de adivinhar o resultado no extrato bancário.</p><a className="inline-flex items-center gap-2 rounded-xl bg-primary-container px-space-lg py-space-sm font-label-lg text-label-lg text-on-primary shadow-md transition-all hover:bg-primary" href="#quero-conhecer"><span>Quero conhecer</span><span className="material-symbols-outlined text-[18px]">chevron_right</span></a></div><div className="flex w-full shrink-0 flex-col gap-3 rounded-2xl bg-surface-container-lowest p-space-lg shadow-md md:w-80"><div className="flex items-center justify-between"><span className="font-label-md text-label-md font-bold text-on-surface">Demonstrativo Sintético</span><span className="material-symbols-outlined text-[20px] text-primary-container">analytics</span></div><div className="space-y-2 pt-2"><div className="flex justify-between font-body-sm text-body-sm"><span className="text-on-surface-variant">(+) Faturamento Bruto</span><span className="font-semibold text-on-surface">R$ 32.480</span></div><div className="flex justify-between font-body-sm text-body-sm text-error"><span>(-) CMV & Fornecedores</span><span className="font-semibold">- R$ 19.820</span></div><div className="flex justify-between font-body-sm text-body-sm text-error"><span>(-) Custos Fixos & Operação</span><span className="font-semibold">- R$ 5.820</span></div><div className="flex justify-between rounded-lg bg-surface-container-low p-2 pt-2 font-title-md text-title-md font-bold text-primary-container"><span>(=) Sobra Real</span><span>R$ 6.840</span></div></div></div></div></section>
  );
}

export function WarmInventory() {
  return (
    <section className="w-full bg-surface-container-low py-space-2xl"><div className="mx-auto max-w-[1440px] px-margin-mobile md:px-margin"><div className="mb-space-xl max-w-2xl"><span className="mb-space-xs block font-label-sm text-label-sm font-bold uppercase tracking-widest text-primary">Controle sem desperdício</span><h2 className="font-headline-lg-mobile text-headline-lg-mobile font-extrabold tracking-tight text-on-surface md:font-headline-lg md:text-headline-lg">Estoque parado também é dinheiro.</h2><p className="mt-2 font-body-lg text-body-lg text-on-surface-variant">Saiba o que vende, o que está parado e o que precisa ser reposto imediatamente.</p></div><div className="mb-space-xl grid grid-cols-1 gap-space-lg md:grid-cols-3">{stockCards.map((card) => (<article className="rounded-2xl bg-surface-container-lowest p-space-lg shadow-sm transition-shadow hover:shadow-md" key={card.title}><div className="mb-space-sm flex items-center justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${card.iconClass}`}><span className="material-symbols-outlined text-[20px]">{card.icon}</span></span><span className={`rounded-full px-2 py-0.5 font-label-sm text-label-sm font-bold ${card.badgeClass}`}>{card.badge}</span></div><h3 className="mb-1 font-headline-sm text-headline-sm font-bold text-on-surface">{card.title}</h3><p className={`my-1 font-display-lg text-display-lg font-extrabold ${card.valueClass}`}>{card.value}</p><p className="font-body-sm text-body-sm text-on-surface-variant">{card.description}</p></article>))}</div><div className="rounded-2xl bg-surface-container-lowest p-space-lg shadow-sm"><p className="mb-space-md flex items-center gap-2 font-title-md text-title-md font-bold text-on-surface"><span className="material-symbols-outlined text-[20px] text-primary">checklist</span>Monitoramento em Tempo Real de Linhas Críticas</p><div className="grid grid-cols-1 gap-space-md md:grid-cols-3">{stockItems.map((item) => (<div className="flex items-center justify-between rounded-xl bg-surface-container-low p-3" key={item.name}><div className="flex items-center gap-3"><span className={`material-symbols-outlined text-[22px] ${item.iconClass}`}>{item.icon}</span><div><p className="font-label-md text-label-md font-bold text-on-surface">{item.name}</p><p className="font-body-sm text-body-sm text-on-surface-variant">{item.detail}</p></div></div><span className={`rounded-md px-2 py-1 font-label-sm text-label-sm font-bold ${item.badgeClass}`}>{item.badge}</span></div>))}</div></div></div></section>
  );
}

export function WarmFinalAndFaq() {
  const [openItems, setOpenItems] = useState(() => new Set([0, 1, 2, 3]));
  const toggle = (index: number) => setOpenItems((current) => { const next = new Set(current); if (next.has(index)) next.delete(index); else next.add(index); return next; });
  return (
    <section className="mx-auto w-full max-w-[1440px] px-margin-mobile py-space-2xl md:px-margin" id="quero-conhecer"><div className="relative mb-space-2xl w-full overflow-hidden rounded-3xl bg-surface-container-high shadow-2xl"><div className="grid grid-cols-1 items-center lg:grid-cols-12"><div className="h-full min-h-[380px] md:min-h-[480px] lg:col-span-6"><Image alt="Cão labrador tranquilo e amigável descansando no chão de madeira de um pet shop charmoso" className="h-full w-full object-cover" height={286} loading="eager" src="/images/pet-shop-labrador.jpg" width={512} /></div><div className="flex flex-col items-start gap-space-md p-space-xl md:p-space-2xl lg:col-span-6"><div className="inline-flex items-center gap-2 rounded-full bg-primary-fixed px-3 py-1 text-on-primary-fixed"><span className="material-symbols-outlined text-[16px]">favorite</span><span className="font-label-sm text-label-sm font-bold uppercase tracking-wider">Cuidado e Controle</span></div><h2 className="font-headline-lg-mobile text-headline-lg-mobile font-extrabold tracking-tight text-on-surface md:font-headline-lg md:text-headline-lg">Cuide do seu negócio como você cuida dos seus clientes.</h2><p className="font-body-lg text-body-lg text-on-surface-variant">Tenha uma visão completa do seu pet shop e tome decisões com mais segurança. O Flux Pet foi desenhado para quem ama animais e quer prosperidade sustentável.</p><div className="flex w-full flex-col items-stretch gap-space-sm pt-2 sm:w-auto sm:flex-row sm:items-center"><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary-container px-space-xl py-4 font-label-lg text-label-lg text-on-primary shadow-[0_8px_24px_-4px_rgba(255,95,21,0.35)] transition-all duration-200 hover:bg-primary" type="button"><span>Quero conhecer o Flux Pet</span><span className="material-symbols-outlined text-[20px]">arrow_forward</span></button></div><p className="font-body-sm text-body-sm text-outline">Demonstração guiada gratuita · Sem necessidade de cartão de crédito no início.</p></div></div></div>
      <div className="mx-auto max-w-3xl pt-space-md" id="faq"><div className="mb-space-xl text-center"><span className="mb-space-xs block font-label-sm text-label-sm font-bold uppercase tracking-widest text-primary">Tire Suas Dúvidas</span><h3 className="font-headline-md text-headline-md font-extrabold text-on-surface">Perguntas Frequentes</h3><p className="mt-1 font-body-md text-body-md text-on-surface-variant">Tudo o que você precisa saber antes de dar o próximo passo.</p></div><div className="space-y-space-sm">{faqs.map(([question, answer], index) => { const open = openItems.has(index); return (<div className="overflow-hidden rounded-2xl bg-surface-container-low transition-colors duration-200" key={question}><button aria-expanded={open} className="flex w-full items-center justify-between gap-4 p-space-md text-left font-title-md text-title-md font-bold text-on-surface focus:outline-none" onClick={() => toggle(index)} type="button"><span>{question}</span><span className={`material-symbols-outlined text-outline transition-transform duration-300 ${open ? "rotate-180" : ""}`}>expand_more</span></button><div className={`${open ? "block" : "hidden"} px-space-md pb-space-md font-body-md text-body-md text-on-surface-variant`}>{answer}</div></div>); })}</div></div>
    </section>
  );
}

export function WarmFooter() {
  return (
    <footer className="w-full border-t border-surface-dim/40 bg-surface-container-low"><div className="mx-auto max-w-[1440px] px-margin-mobile py-space-xl md:px-margin"><div className="flex flex-col items-center justify-between gap-space-lg border-b border-surface-dim/30 pb-space-lg md:flex-row"><div className="flex flex-col items-center gap-space-sm text-center sm:flex-row sm:gap-space-md sm:text-left"><BrandLogo compact premium={false} /><span className="hidden text-surface-dim sm:inline">|</span><p className="font-body-md text-body-md text-on-surface-variant">Gestão inteligente para pet shops.</p></div><nav className="flex flex-wrap items-center justify-center gap-space-md sm:gap-space-lg"><a className="font-body-sm text-body-sm text-on-surface-variant transition-colors hover:text-on-surface" href="#recursos">Recursos</a><span className="text-xs text-outline-variant">·</span><a className="font-body-sm text-body-sm text-on-surface-variant transition-colors hover:text-on-surface" href="#como-funciona">Como funciona</a><span className="text-xs text-outline-variant">·</span><a className="font-body-sm text-body-sm text-on-surface-variant transition-colors hover:text-on-surface" href="#faq">FAQ</a><span className="text-xs text-outline-variant">·</span><a className="font-body-sm text-body-sm text-on-surface-variant transition-colors hover:text-on-surface" href="#quero-conhecer">Contato</a></nav></div><div className="flex flex-col items-center justify-between gap-space-sm pt-space-md text-center sm:flex-row sm:text-left"><p className="font-body-sm text-body-sm text-on-surface-variant">© 2026 Flux Soluções Digitais Ltda. Todos os direitos reservados.</p><p className="font-label-sm text-label-sm uppercase tracking-wider text-outline">Tecnologia Veterinária & Concierge</p></div></div></footer>
  );
}
