import Image from "next/image";

const pillars = [
  { number: "01. Fluxo de Caixa", icon: "point_of_sale", iconClass: "bg-primary-fixed text-primary", title: "Vendas", lead: "Saiba quanto vende.", text: "Monitore cada checkout, ticket médio por cliente, pagamentos em cartão, Pix e crediário em tempo real." },
  { number: "02. Controle Físico", icon: "inventory_2", iconClass: "bg-secondary-container text-secondary", title: "Estoque", lead: "Saiba o que tem.", text: "Rastreie sacarias, farmácia veterinária, data de validade e alertas de reposição antes do estoque zerar." },
  { number: "03. Resultado Líquido", icon: "savings", iconClass: "bg-tertiary-fixed text-tertiary", title: "Lucro", lead: "Saiba quanto ganha.", text: "Cálculo automático de CMV e custos fixos para saber exatamente a sobra real no final de cada expediente." },
];

export function WarmPillars() {
  return (
    <section className="w-full bg-surface-container-low py-space-2xl" id="recursos"><div className="mx-auto flex max-w-[1440px] flex-col items-center px-margin-mobile text-center md:px-margin"><span className="mb-space-xs font-label-sm text-label-sm font-bold uppercase tracking-widest text-primary">Visão Estratégica Sem Ruído</span><h2 className="max-w-3xl font-headline-lg-mobile text-headline-lg-mobile font-extrabold leading-snug text-on-surface md:font-headline-lg md:text-headline-lg">Seu pet shop tem muitos números. O <span className="text-primary-container">Flux Pet</span> transforma tudo em clareza.</h2><p className="mb-space-xl mt-space-sm max-w-xl font-body-lg text-body-lg text-on-surface-variant">Elimine o estresse do fim do mês com três pilares consolidados em uma interface límpida e descomplicada.</p><div className="grid w-full max-w-5xl grid-cols-1 gap-space-lg text-left md:grid-cols-3">{pillars.map((pillar) => (<article className="group rounded-2xl bg-surface-container-lowest p-space-xl shadow-sm transition-all duration-200 hover:shadow-md" key={pillar.title}><div className={`mb-space-md flex h-12 w-12 items-center justify-center rounded-xl transition-transform group-hover:scale-110 ${pillar.iconClass}`}><span className="material-symbols-outlined text-[26px]">{pillar.icon}</span></div><span className="mb-1 block font-label-sm text-label-sm uppercase tracking-wider text-outline">{pillar.number}</span><h3 className="mb-space-xs font-headline-sm text-headline-sm font-bold text-on-surface">{pillar.title}</h3><p className="mb-3 font-body-lg text-body-lg font-medium text-on-surface-variant">{pillar.lead}</p><p className="font-body-sm text-body-sm text-on-surface-variant">{pillar.text}</p></article>))}</div></div></section>
  );
}

export function WarmControl() {
  return (
    <section className="mx-auto w-full max-w-[1440px] px-margin-mobile py-space-2xl md:px-margin" id="como-funciona"><div className="grid grid-cols-1 items-center gap-space-xl lg:grid-cols-12"><div className="relative lg:col-span-6"><div className="relative w-full overflow-hidden rounded-3xl bg-surface-container shadow-xl"><Image alt="Atendente de pet shop sorrindo enquanto acaricia um cachorro amigável no balcão de atendimento" className="h-[480px] w-full object-cover" height={382} loading="eager" src="/images/pet-shop-atendimento.jpg" width={512} /><div className="absolute left-5 top-5 flex items-center gap-2 rounded-xl bg-surface-container-lowest/90 px-4 py-2 shadow-sm backdrop-blur-md"><span className="h-2.5 w-2.5 rounded-full bg-primary-container" /><span className="font-label-sm text-label-sm font-bold text-on-surface">Atendimento 100% humanizado</span></div></div></div><div className="flex flex-col items-start gap-space-md lg:col-span-6"><div className="inline-flex items-center gap-2 rounded-full bg-primary-fixed px-space-md py-1 text-on-primary-fixed-variant"><span className="material-symbols-outlined text-[16px]">verified_user</span><span className="font-label-sm text-label-sm font-bold uppercase tracking-wider">Gestão Unificada</span></div><h2 className="font-headline-lg-mobile text-headline-lg-mobile font-extrabold tracking-tight text-on-surface md:font-headline-lg md:text-headline-lg">Tudo sob controle.</h2><p className="max-w-lg font-body-lg text-body-lg text-on-surface-variant">Do atendimento ao fechamento do mês, você acompanha a operação em um só lugar. Menos tempo alimentando cadastros manuais, mais tempo dando atenção para quem realmente importa.</p><div className="grid w-full max-w-md grid-cols-2 gap-space-sm pt-space-xs">{["Vendas", "Estoque", "Financeiro", "Indicadores"].map((label) => (<div className="flex items-center gap-2.5 rounded-xl bg-surface-container-low px-space-md py-space-sm" key={label}><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary-container"><span className="material-symbols-outlined text-[14px] text-on-primary">check</span></span><span className="font-title-md text-title-md font-bold text-on-surface">{label}</span></div>))}</div><div className="pt-space-sm"><a className="group inline-flex items-center gap-2 font-label-lg text-label-lg font-bold text-primary hover:text-primary-container" href="#dashboard"><span>Descobrir como funciona na prática</span><span className="material-symbols-outlined text-[18px] transition-transform group-hover:translate-x-1">arrow_forward</span></a></div></div></div></section>
  );
}
