import Image from "next/image";
import { BrandLogo } from "@/components/common/BrandLogo";

export function WarmHeader() {
  return (
    <header className="fixed left-0 top-0 z-50 w-full border-b border-surface-dim/40 bg-surface/90 backdrop-blur-md"><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-margin-mobile md:px-margin"><a className="group" href="#recursos"><BrandLogo premium={false} /></a><nav className="hidden items-center gap-space-lg md:flex"><a className="font-bold text-primary transition-colors" href="#recursos">Recursos</a><a className="font-label-lg text-label-lg text-on-surface-variant transition-colors hover:text-on-surface" href="#como-funciona">Como funciona</a><a className="font-label-lg text-label-lg text-on-surface-variant transition-colors hover:text-on-surface" href="#faq">FAQ</a></nav><div className="flex items-center gap-space-md"><a className="inline-flex items-center justify-center rounded-full bg-primary-container px-space-lg py-space-sm font-label-lg text-label-lg text-on-primary shadow-[0_8px_24px_-4px_rgba(255,95,21,0.35)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-primary" href="#quero-conhecer">Quero conhecer</a><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary"><span className="material-symbols-outlined text-[18px] text-on-primary">person</span></div></div></div></header>
  );
}

export function WarmHero() {
  return (
    <section className="relative mx-auto w-full max-w-[1440px] overflow-hidden px-margin-mobile pb-space-2xl pt-space-xl md:px-margin"><div className="grid grid-cols-1 items-center gap-space-xl lg:grid-cols-12"><div className="z-10 flex flex-col items-start gap-space-md lg:col-span-6"><div className="inline-flex items-center gap-2 rounded-full bg-surface-container-high px-space-md py-1.5 shadow-sm"><span className="h-2 w-2 animate-pulse rounded-full bg-primary-container" /><span className="font-label-sm text-label-sm uppercase tracking-wider text-on-surface">GESTÃO INTELIGENTE PARA PET SHOPS</span></div><h1 className="font-display-lg-mobile text-display-lg-mobile font-extrabold tracking-tight text-on-surface md:font-display-lg md:text-display-lg">Você sabe tudo sobre o seu <span className="text-primary-container">pet shop</span>.</h1><p className="max-w-xl font-body-lg text-body-lg text-on-surface-variant">Vendas, estoque, financeiro e resultados em um só lugar. Tenha visão cristalina do seu negócio sem perder a leveza do atendimento diário.</p><div className="flex w-full flex-col items-start gap-space-md pt-space-xs sm:w-auto sm:flex-row sm:items-center"><a className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary-container px-space-xl py-4 font-label-lg text-label-lg text-on-primary shadow-[0_8px_24px_-4px_rgba(255,95,21,0.35)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-primary sm:w-auto" href="#quero-conhecer"><span>Quero conhecer o Flux Pet</span><span className="material-symbols-outlined text-[20px]">arrow_forward</span></a></div><p className="flex items-center gap-1.5 font-body-sm text-body-sm text-outline"><span className="material-symbols-outlined text-[16px] text-primary">verified</span>Simples para usar. Completo para controlar.</p><div className="grid w-full max-w-md grid-cols-3 gap-space-md pt-space-md">{[["+400", "Lojas ativas"], ["100%", "Em nuvem"], ["Zero", "Planilhas lentas"]].map(([value, label]) => (<div className="rounded-xl bg-surface-container-low p-space-sm" key={label}><span className="block font-headline-sm text-headline-sm font-bold text-on-surface">{value}</span><span className="font-label-sm text-label-sm text-on-surface-variant">{label}</span></div>))}</div></div>
      <div className="relative flex w-full items-center justify-center lg:col-span-6"><div className="pointer-events-none absolute -right-8 -top-12 -z-10 h-80 w-80 rounded-full bg-primary-fixed opacity-40 blur-3xl" /><div className="relative w-full overflow-hidden rounded-3xl bg-surface-container shadow-2xl"><Image alt="Golden Retriever e gato em um pet shop boutique acolhedor e moderno" className="h-[460px] w-full object-cover md:h-[540px]" height={382} priority src="/images/pet-shop-hero.jpg" width={512} /><div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6 flex items-center justify-between text-on-primary"><div className="flex items-center gap-2"><span className="material-symbols-outlined text-[20px] text-primary-fixed">storefront</span><span className="font-label-md text-label-md font-semibold tracking-wide">Paws & Co. Boutique</span></div><span className="rounded-full bg-surface-container-lowest/20 px-3 py-1 font-label-sm text-label-sm text-on-primary backdrop-blur-md">Operação Sincronizada</span></div></div>
        <div className="absolute -bottom-8 -left-2 w-[90%] max-w-[340px] rounded-2xl bg-surface-container-lowest p-space-md shadow-[0_20px_45px_-10px_rgba(45,35,25,0.18)] backdrop-blur-md transition-transform duration-200 hover:-translate-y-1 md:-bottom-6 md:-left-8"><div className="flex items-center justify-between pb-3"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-emerald-500" /><span className="font-label-md text-label-md font-bold text-on-surface">Resumo em Tempo Real</span></div><span className="font-label-sm text-label-sm font-semibold uppercase text-outline">Hoje</span></div><div className="grid grid-cols-3 gap-2 rounded-xl bg-surface-container-low px-2 py-2 text-center"><div><span className="block font-label-sm text-label-sm text-on-surface-variant">Faturamento</span><span className="font-title-md text-title-md font-extrabold text-on-surface">R$ 32.480</span></div><div><span className="block font-label-sm text-label-sm text-on-surface-variant">Lucro</span><span className="font-title-md text-title-md font-extrabold text-primary-container">R$ 6.840</span></div><div><span className="block font-label-sm text-label-sm text-on-surface-variant">Margem</span><span className="font-title-md text-title-md font-extrabold text-emerald-600">30,2%</span></div></div><div className="flex items-center justify-between gap-3 pt-3"><div className="flex flex-col"><span className="font-label-sm text-label-sm text-on-surface-variant">Tendência diária</span><span className="flex items-center gap-0.5 font-label-md text-label-md font-bold text-emerald-700"><span className="material-symbols-outlined text-[16px]">trending_up</span>+18,4%</span></div><div className="flex h-9 w-32 items-end"><svg className="h-full w-full overflow-visible text-primary-container" fill="none" viewBox="0 0 120 30"><path d="M0 25 C 20 22, 35 28, 50 15 C 65 2, 80 18, 95 10 C 105 4, 115 6, 120 2" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" /><circle className="fill-primary-container" cx="120" cy="2" r="3.5" /></svg></div></div></div>
      </div></div></section>
  );
}
